In [9]:
import numpy as np;

In [10]:
n=np.array((1,2,3,4,5));#it accepts 2 arguments 2nd one is crete for n dimensions
m=np.array((1,2,3),ndmin=5)
n
m

array([[[[[1, 2, 3]]]]])

In [11]:
n.ndim
# return dimensions

1

In [13]:
print(m[0,0,0,0,1]);

2


In [15]:
ex=np.array((1,2,3),dtype='i');
(ex.dtype) #for strings s , float f

dtype('int64')

In [17]:
#conversion
ex2=np.array(('1','2'))
new=ex2.astype('i')
new


array([1, 2], dtype=int32)

In [19]:
#copy and view
#copy makes new object
#while iew use same references
y=np.array((1,2,3));
o=y.copy()
o[1]=4
y

array([1, 2, 3])

In [20]:
y=np.array((1,2,3));
o=y.view()
o[1]=4
y

array([1, 4, 3])

In [23]:
o=np.array([[1,2,3]])
o.shape #1-row 3-col

(1, 3)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)#if we give not correct num of elemnts error

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)#for loop

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x) #it for n dimension so we dont want to use n for loops

In [ ]:

for idx, x in np.ndenumerate(arr):
  print(idx, x) #index

In [28]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)#vertical

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) #horizontal

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr) #both horizontal as well as vertical

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [31]:
arr=np.array([1,2,3,4])
newarray=np.array_split(arr,3);
newarray

[array([1, 2]), array([3]), array([4])]

In [42]:
arr=np.array([[1,2,3,4]])
newarray=np.array_split(arr,4,axis=1);
ans=[]
for i in newarray:

  ans.append(i.reshape(1))
print(ans)
newarray

[array([1]), array([2]), array([3]), array([4])]


[array([[1]]), array([[2]]), array([[3]]), array([[4]])]

In [43]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)#search

(array([3, 5, 6]),)


In [45]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)#even-index

(array([1, 3, 5, 7]),)


In [46]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)#it takes value

1


In [47]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x) #form right

2


In [ ]:
np.sort()

In [49]:
arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)#filter

[41 43]


In [48]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [50]:
from numpy import random

x = random.randint(100)

print(x)#random form 0-100

7


In [51]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[19 67 86  6 25]
 [71 25 72 43 54]
 [71 26  3 41 52]]


In [52]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 3 5 3]
 [9 9 3 3 3]
 [5 7 5 9 3]]
